spring.application.name=axon-resource-booking
axon.axonserver.enabled=false
axon.serializer.general=jackson
axon.serializer.events=jackson
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/axon_resource_booking}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/docs
